export EulerLagrangeSystem, ControlledEulerLagrangeSystem
export Rn, Rmxn

"""
Abstract type representing an Euler-Lagrange system

An Euler-Lagrange system (e.g., a rigid body) is a dynamical system with two
state vectors - the generalized coordinates (`q`), and the generalized velocities
(`q_dot`).

The dynamics of the E-L system are given by the equation
    d/dt(∂ℓ/∂q_dot) - ∂ℓ/∂q = F
where `ℓ` is the Lagrangian of the system, and `F` is the vector of generalized forces.

See also: `lagrangian`, `forces`
"""
abstract type EulerLagrangeSystem end

"""
Abstract type representing an Euler-Lagrange system with a controller

An Euler-Lagrange system with a controller is a dynamical system with three
state vectors - the generalized coordinates (`q`), the generalized velocities
(`q_dot`), and the internal state of the controller (`x_i`).

The dynamics of the system are given by the equation
    d/dt(∂ℓ/∂q_dot) - ∂ℓ/∂q = F + τ
where `ℓ` is the Lagrangian of the system, `F` is the vector of generalized forces,
and `τ` are the forces generated by the control system.

See also: `lagrangian`, `forces`, `control_law`
"""
abstract type ControlledEulerLagrangeSystem end

"Shortcut for an AbstractVector{<:Real}"
const Rn = AbstractVector{<:Real}
"Shortcut for an AbstractMatrix{<:Real}"
const Rmxn = AbstractMatrix{<:Real}
